DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS author;

CREATE TABLE authors (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE books (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255),
  author_id INT REFERENCES authors(id)
);